ruby '2.0.0'
source 'https://rubygems.org'

gem 'thor', '~>0.19'
gem 'xcodeproj', '~>0.28'
gem 'zipruby', '~>0.3'
gem 'plist', '~>3.2'
gem 'rest-client', '~>1.8'
gem 'colorize', '~>0.7'

group :development do
  gem 'pry', '~>0.10'
  gem 'pry-byebug', '~>3.3'
  gem 'awesome_print', '~>1.6'
end
