require 'ostruct'
require 'json'
require 'uri'
require 'fileutils'
require 'pathname'
require 'tempfile'

require 'thor'
require 'xcodeproj'
require 'zipruby'
require 'plist'
require 'rest-client'
require 'colorize'
require 'awesome_print'
require 'mini_magick'
require 'aws-sdk'

require 'channel-cli/version'
require 'channel-cli/utility'
require 'channel-cli/config'
require 'channel-cli/helpers'
require 'channel-cli/chan'
